export type ThemeId = 'pulse' | 'sunset' | 'botanic' | 'midnight';

export interface ThemeDefinition {
  id: ThemeId;
  name: string;
  tagline: string;
  description: string;
  accentHue: number;
  swatches: {
    primary: { light: string; dark: string; lightHex: string; darkHex: string };
    highlight: { light: string; dark: string; lightHex: string; darkHex: string };
    surface: { light: string; dark: string; lightHex: string; darkHex: string };
  };
  pairs: Array<{
    name: string;
    fgName: string;
    bgName: string;
    lightFg: string;
    lightBg: string;
    darkFg: string;
    darkBg: string;
  }>;
}

export const THEMES: ThemeDefinition[] = [
  {
    id: 'pulse',
    name: 'Pulse',
    tagline: 'Electric Studio',
    description: 'Deep slate & indigo canvas with an electric cyan signature accent. Modern, precise, tech-forward.',
    accentHue: 195,
    swatches: {
      primary: {
        light: 'oklch(0.45 0.18 265)',
        dark: 'oklch(0.68 0.17 265)',
        lightHex: '#3D34B3',
        darkHex: '#8479FF',
      },
      highlight: {
        light: 'oklch(0.48 0.18 195)',
        dark: 'oklch(0.82 0.16 175)',
        lightHex: '#087EA4',
        darkHex: '#2DD4BF',
      },
      surface: {
        light: 'oklch(0.99 0.002 240)',
        dark: 'oklch(0.14 0.015 260)',
        lightHex: '#FAFBFD',
        darkHex: '#0D0E15',
      },
    },
    pairs: [
      {
        name: 'Default Body Text',
        fgName: 'Foreground',
        bgName: 'Background',
        lightFg: '#18181B',
        lightBg: '#FAFBFD',
        darkFg: '#F4F4F5',
        darkBg: '#0D0E15',
      },
      {
        name: 'Card Content',
        fgName: 'Card Foreground',
        bgName: 'Card',
        lightFg: '#18181B',
        lightBg: '#FFFFFF',
        darkFg: '#F4F4F5',
        darkBg: '#141620',
      },
      {
        name: 'Primary Action Button',
        fgName: 'Primary Foreground',
        bgName: 'Primary',
        lightFg: '#FFFFFF',
        lightBg: '#3D34B3',
        darkFg: '#0D0E15',
        darkBg: '#8479FF',
      },
      {
        name: 'Highlight Accent Element',
        fgName: 'Highlight Foreground',
        bgName: 'Highlight',
        lightFg: '#FFFFFF',
        lightBg: '#087EA4',
        darkFg: '#0D0E15',
        darkBg: '#2DD4BF',
      },
      {
        name: 'Secondary Action Button',
        fgName: 'Secondary Foreground',
        bgName: 'Secondary',
        lightFg: '#18181B',
        lightBg: '#EAEBF2',
        darkFg: '#F4F4F5',
        darkBg: '#222533',
      },
      {
        name: 'Muted Caption Text',
        fgName: 'Muted Foreground',
        bgName: 'Background',
        lightFg: '#52525B',
        lightBg: '#FAFBFD',
        darkFg: '#A1A1AA',
        darkBg: '#0D0E15',
      },
      {
        name: 'Destructive Button',
        fgName: 'Destructive Foreground',
        bgName: 'Destructive',
        lightFg: '#FFFFFF',
        lightBg: '#DC2626',
        darkFg: '#0D0E15',
        darkBg: '#F87171',
      },
      {
        name: 'Success Badge / Banner',
        fgName: 'Success Foreground',
        bgName: 'Success',
        lightFg: '#FFFFFF',
        lightBg: '#047857',
        darkFg: '#0D0E15',
        darkBg: '#34D399',
      },
      {
        name: 'Warning Banner',
        fgName: 'Warning Foreground',
        bgName: 'Warning',
        lightFg: '#18181B',
        lightBg: '#D97706',
        darkFg: '#18181B',
        darkBg: '#FBBF24',
      },
      {
        name: 'Info Notice',
        fgName: 'Info Foreground',
        bgName: 'Info',
        lightFg: '#FFFFFF',
        lightBg: '#2563EB',
        darkFg: '#0D0E15',
        darkBg: '#60A5FA',
      },
    ],
  },
  {
    id: 'sunset',
    name: 'Sunset',
    tagline: 'Warm Terracotta',
    description: 'Warm sandstone canvas with burnt terracotta primary and amber glow. Tactile, organic, editorial.',
    accentHue: 55,
    swatches: {
      primary: {
        light: 'oklch(0.50 0.19 38)',
        dark: 'oklch(0.72 0.17 40)',
        lightHex: '#C2410C',
        darkHex: '#FB923C',
      },
      highlight: {
        light: 'oklch(0.52 0.18 55)',
        dark: 'oklch(0.80 0.16 65)',
        lightHex: '#B45309',
        darkHex: '#FBBF24',
      },
      surface: {
        light: 'oklch(0.985 0.008 70)',
        dark: 'oklch(0.14 0.018 45)',
        lightHex: '#FAF7F2',
        darkHex: '#171210',
      },
    },
    pairs: [
      {
        name: 'Default Body Text',
        fgName: 'Foreground',
        bgName: 'Background',
        lightFg: '#261D1A',
        lightBg: '#FAF7F2',
        darkFg: '#F7F3EE',
        darkBg: '#171210',
      },
      {
        name: 'Card Content',
        fgName: 'Card Foreground',
        bgName: 'Card',
        lightFg: '#261D1A',
        lightBg: '#FFFFFF',
        darkFg: '#F7F3EE',
        darkBg: '#221B17',
      },
      {
        name: 'Primary Action Button',
        fgName: 'Primary Foreground',
        bgName: 'Primary',
        lightFg: '#FFFFFF',
        lightBg: '#C2410C',
        darkFg: '#171210',
        darkBg: '#FB923C',
      },
      {
        name: 'Highlight Accent Element',
        fgName: 'Highlight Foreground',
        bgName: 'Highlight',
        lightFg: '#FFFFFF',
        lightBg: '#B45309',
        darkFg: '#171210',
        darkBg: '#FBBF24',
      },
      {
        name: 'Secondary Action Button',
        fgName: 'Secondary Foreground',
        bgName: 'Secondary',
        lightFg: '#261D1A',
        lightBg: '#EDE7DE',
        darkFg: '#F7F3EE',
        darkBg: '#2C231E',
      },
      {
        name: 'Muted Caption Text',
        fgName: 'Muted Foreground',
        bgName: 'Background',
        lightFg: '#6E5C53',
        lightBg: '#FAF7F2',
        darkFg: '#B39E92',
        darkBg: '#171210',
      },
      {
        name: 'Destructive Button',
        fgName: 'Destructive Foreground',
        bgName: 'Destructive',
        lightFg: '#FFFFFF',
        lightBg: '#DC2626',
        darkFg: '#171210',
        darkBg: '#F87171',
      },
      {
        name: 'Success Badge / Banner',
        fgName: 'Success Foreground',
        bgName: 'Success',
        lightFg: '#FFFFFF',
        lightBg: '#047857',
        darkFg: '#171210',
        darkBg: '#34D399',
      },
      {
        name: 'Warning Banner',
        fgName: 'Warning Foreground',
        bgName: 'Warning',
        lightFg: '#18181B',
        lightBg: '#D97706',
        darkFg: '#18181B',
        darkBg: '#FBBF24',
      },
      {
        name: 'Info Notice',
        fgName: 'Info Foreground',
        bgName: 'Info',
        lightFg: '#FFFFFF',
        lightBg: '#2563EB',
        darkFg: '#171210',
        darkBg: '#60A5FA',
      },
    ],
  },
  {
    id: 'botanic',
    name: 'Botanic',
    tagline: 'Sage & Emerald',
    description: 'Moss-tinted canvas with emerald green primary and radiant lime highlights. Clean, fresh, organic.',
    accentHue: 135,
    swatches: {
      primary: {
        light: 'oklch(0.42 0.14 150)',
        dark: 'oklch(0.70 0.16 150)',
        lightHex: '#047857',
        darkHex: '#34D399',
      },
      highlight: {
        light: 'oklch(0.45 0.15 130)',
        dark: 'oklch(0.82 0.16 135)',
        lightHex: '#15803D',
        darkHex: '#86EFAC',
      },
      surface: {
        light: 'oklch(0.985 0.006 145)',
        dark: 'oklch(0.13 0.018 150)',
        lightHex: '#F7FAF8',
        darkHex: '#0E1712',
      },
    },
    pairs: [
      {
        name: 'Default Body Text',
        fgName: 'Foreground',
        bgName: 'Background',
        lightFg: '#132117',
        lightBg: '#F7FAF8',
        darkFg: '#EEF6F0',
        darkBg: '#0E1712',
      },
      {
        name: 'Card Content',
        fgName: 'Card Foreground',
        bgName: 'Card',
        lightFg: '#132117',
        lightBg: '#FFFFFF',
        darkFg: '#EEF6F0',
        darkBg: '#152219',
      },
      {
        name: 'Primary Action Button',
        fgName: 'Primary Foreground',
        bgName: 'Primary',
        lightFg: '#FFFFFF',
        lightBg: '#047857',
        darkFg: '#0E1712',
        darkBg: '#34D399',
      },
      {
        name: 'Highlight Accent Element',
        fgName: 'Highlight Foreground',
        bgName: 'Highlight',
        lightFg: '#FFFFFF',
        lightBg: '#15803D',
        darkFg: '#0E1712',
        darkBg: '#86EFAC',
      },
      {
        name: 'Secondary Action Button',
        fgName: 'Secondary Foreground',
        bgName: 'Secondary',
        lightFg: '#132117',
        lightBg: '#E4ECE5',
        darkFg: '#EEF6F0',
        darkBg: '#1C2E22',
      },
      {
        name: 'Muted Caption Text',
        fgName: 'Muted Foreground',
        bgName: 'Background',
        lightFg: '#4B6252',
        lightBg: '#F7FAF8',
        darkFg: '#9EB8A5',
        darkBg: '#0E1712',
      },
      {
        name: 'Destructive Button',
        fgName: 'Destructive Foreground',
        bgName: 'Destructive',
        lightFg: '#FFFFFF',
        lightBg: '#DC2626',
        darkFg: '#0E1712',
        darkBg: '#F87171',
      },
      {
        name: 'Success Badge / Banner',
        fgName: 'Success Foreground',
        bgName: 'Success',
        lightFg: '#FFFFFF',
        lightBg: '#047857',
        darkFg: '#0E1712',
        darkBg: '#34D399',
      },
      {
        name: 'Warning Banner',
        fgName: 'Warning Foreground',
        bgName: 'Warning',
        lightFg: '#18181B',
        lightBg: '#D97706',
        darkFg: '#18181B',
        darkBg: '#FBBF24',
      },
      {
        name: 'Info Notice',
        fgName: 'Info Foreground',
        bgName: 'Info',
        lightFg: '#FFFFFF',
        lightBg: '#2563EB',
        darkFg: '#0E1712',
        darkBg: '#60A5FA',
      },
    ],
  },
  {
    id: 'midnight',
    name: 'Midnight',
    tagline: 'Obsidian & Neon',
    description: 'True obsidian dark-first canvas with electric purple and cyan neon accents. High-contrast, futuristic cyberpunk.',
    accentHue: 160,
    swatches: {
      primary: {
        light: 'oklch(0.42 0.20 290)',
        dark: 'oklch(0.72 0.18 290)',
        lightHex: '#6D28D9',
        darkHex: '#A78BFA',
      },
      highlight: {
        light: 'oklch(0.38 0.15 160)',
        dark: 'oklch(0.84 0.18 160)',
        lightHex: '#0F766E',
        darkHex: '#5EEAD4',
      },
      surface: {
        light: 'oklch(0.985 0.004 280)',
        dark: 'oklch(0.11 0.018 275)',
        lightHex: '#FAF8FC',
        darkHex: '#090812',
      },
    },
    pairs: [
      {
        name: 'Default Body Text',
        fgName: 'Foreground',
        bgName: 'Background',
        lightFg: '#14111E',
        lightBg: '#FAF8FC',
        darkFg: '#F5F3FF',
        darkBg: '#090812',
      },
      {
        name: 'Card Content',
        fgName: 'Card Foreground',
        bgName: 'Card',
        lightFg: '#14111E',
        lightBg: '#FFFFFF',
        darkFg: '#F5F3FF',
        darkBg: '#121020',
      },
      {
        name: 'Primary Action Button',
        fgName: 'Primary Foreground',
        bgName: 'Primary',
        lightFg: '#FFFFFF',
        lightBg: '#6D28D9',
        darkFg: '#090812',
        darkBg: '#A78BFA',
      },
      {
        name: 'Highlight Accent Element',
        fgName: 'Highlight Foreground',
        bgName: 'Highlight',
        lightFg: '#FFFFFF',
        lightBg: '#0F766E',
        darkFg: '#090812',
        darkBg: '#5EEAD4',
      },
      {
        name: 'Secondary Action Button',
        fgName: 'Secondary Foreground',
        bgName: 'Secondary',
        lightFg: '#14111E',
        lightBg: '#EDE9F5',
        darkFg: '#F5F3FF',
        darkBg: '#1C182E',
      },
      {
        name: 'Muted Caption Text',
        fgName: 'Muted Foreground',
        bgName: 'Background',
        lightFg: '#5A526E',
        lightBg: '#FAF8FC',
        darkFg: '#A79DBF',
        darkBg: '#090812',
      },
      {
        name: 'Destructive Button',
        fgName: 'Destructive Foreground',
        bgName: 'Destructive',
        lightFg: '#FFFFFF',
        lightBg: '#DC2626',
        darkFg: '#090812',
        darkBg: '#F87171',
      },
      {
        name: 'Success Badge / Banner',
        fgName: 'Success Foreground',
        bgName: 'Success',
        lightFg: '#FFFFFF',
        lightBg: '#047857',
        darkFg: '#090812',
        darkBg: '#34D399',
      },
      {
        name: 'Warning Banner',
        fgName: 'Warning Foreground',
        bgName: 'Warning',
        lightFg: '#18181B',
        lightBg: '#D97706',
        darkFg: '#18181B',
        darkBg: '#FBBF24',
      },
      {
        name: 'Info Notice',
        fgName: 'Info Foreground',
        bgName: 'Info',
        lightFg: '#FFFFFF',
        lightBg: '#2563EB',
        darkFg: '#090812',
        darkBg: '#60A5FA',
      },
    ],
  },
];

export function getTheme(id: ThemeId): ThemeDefinition {
  const found = THEMES.find((t) => t.id === id);
  return found || THEMES[0];
}
